import pandas as pd
import numpy as np
import os.path

path = os.getcwd()

loc = pd.read_csv(path+'/data/Local_Authority_District_to_Region_December_2018_Lookup_in_England.csv')
loc = loc.rename(columns={"LAD18NM":"location","RGN18NM":"region"})
loc = loc.drop(columns=['LAD18CD','RGN18CD','FID'], axis=1)
loc = loc.append({'location' : 'London' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Leyton' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'West End' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Uxbridge' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Feltham' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Hertfordshire' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Essex' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Bristol' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Edinburgh' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Glasgow' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Hampshire' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Staffordshire' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Stoke On Trent' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Belfast' , 'region' : 'Northern Ireland'} , ignore_index=True)
loc = loc.append({'location' : 'Basingstoke' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'West Malling' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Telford' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Banbury' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Twickenham' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Kingston Upon Hull' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Ossett' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Keighley' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Northallerton' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'South Yorkshire' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Morley' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Cardiff' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Broughton' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Bath' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Cheadle' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Gloucestershire' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'St Neots' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Newbury' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Sidmouth' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Stratford' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Hertford' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Witham' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Dummer' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Oxfordshire' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Brighton' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Hatfield' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Wrexham' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Handforth' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Billingshurst' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Royal Tunbridge Wells' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'West Bromwich' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Shrewsbury' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Cambridgeshire' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Staines' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Saint Columb Major' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Spalding' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Thame' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Worksop' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Hoddesdon' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Devon' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Westbury' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Gibraltar' , 'region' : 'Offshore'} , ignore_index=True)
loc = loc.append({'location' : 'Cambridge Huntingdon St Neots Peterborough' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Salisbury' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Folkestone' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Poulton-Le-Fylde' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Brockenhurst' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Beckington' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Crewe' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Teesport' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Caernarfon' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Chester' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Billingham' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Erdington' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Pitsea' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Warwickshire' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Rushden' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Finchingfield' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'West Drayton' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Nuneaton' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Nether Poppleton' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Taunton' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Widnes' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Stratford-Upon-Avon' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Surrey' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Wymondham' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Aldwych' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Halesowen' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Chandlers Ford' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'North East England' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'South West England' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'West Midlands' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Newcastle' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Uk Wide' , 'region' : np.NaN} , ignore_index=True)
loc = loc.append({'location' : 'England' , 'region' : np.NaN} , ignore_index=True)
loc = loc.append({'location' : 'Cannock' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Hemel Hempstead' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'West Yorkshire' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Aberdeen' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Ross-On-Wye' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Dorchester' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Nantwich' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Tilbury' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Bedfordshire' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Dorset' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Reigate' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Blackburn' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Livingston' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Maidenhead' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Camberley' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Kent' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Newport' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Atherstone' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Hedge End' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Frimley' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Dorking' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Egham' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Cleckheaton' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Newark Upon Trent' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Corsham (Wiltshire)' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : "Bishop'S Stortford" , 'region' : 'East'} , ignore_index=True)
loc = loc.append({'location' : 'Houghton Le Spring' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Suffolk' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Newry' , 'region' : 'Northern Ireland'} , ignore_index=True)
loc = loc.append({'location' : 'Skelmersdale' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'St Columb Major' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Bridgend' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Alfreton' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Lisburn' , 'region' : 'Northern Ireland'} , ignore_index=True)
loc = loc.append({'location' : 'Cabharstadh' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Tonbridge' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Bexhill-On-Sea' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Ellesmere Port' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Norfolk' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'High Wycombe' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Macclesfield' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Burgess Hill' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Scunthorpe' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Newton Abbot' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Stanford-Le-Hope' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Windsor' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Romford' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Nottinghamshire' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Wetherby' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Amersham' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'East Grinstead' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Borehamwood' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Buxton' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Knutsford' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Aylesbury' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Northwich' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Dundee' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Stretford' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Turnford' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Scotland' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Northern Ireland' , 'region' : 'Northern Ireland'} , ignore_index=True)
loc = loc.append({'location' : 'Burton Upon Trent' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Berkshire' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Canary Wharf' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Stamford' , 'region' : np.NaN} , ignore_index=True)
loc = loc.append({'location' : 'Newton Aycliffe' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Trafford Park' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Haverhill' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Flixton' , 'region' : np.NaN} , ignore_index=True)
loc = loc.append({'location' : 'Middleton' , 'region' : np.NaN} , ignore_index=True)
loc = loc.append({'location' : 'Deeside' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Farringdon' , 'region' : np.NaN} , ignore_index=True)
loc = loc.append({'location' : 'Holborn' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Redhill' , 'region' : np.NaN} , ignore_index=True)
loc = loc.append({'location' : 'Durham' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Cheshire' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Kensington' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Sale' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Sandwich' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Washington' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Abingdon' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Attleborough' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Farnborough' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Bracknell' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Hitchin' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'B633Bl' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'St Helens' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Irlam' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Worcestershire' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Epsom' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Hornchurch' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Winnersh' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Manchester City Centre' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Haddenham' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Wisbech' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Bury St Edmunds' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Welwyn Garden City' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Derbyshire' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Skegness' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Windlesham' , 'region' : 'South East'} , ignore_index=True)

loc.location = loc.location.str.title()
loc['country'] = 'UK'
loc.to_csv(path + '/data/locations_UK.csv', index=False)