import pandas as pd
import os.path

path = os.getcwd()

loc = pd.read_csv(path+'/data/Local_Authority_District_to_Region_December_2018_Lookup_in_England.csv')
loc = loc.rename(columns={"LAD18NM":"location","RGN18NM":"region"})
loc = loc.drop(columns=['LAD18CD','RGN18CD','FID'], axis=1)
loc = loc.append({'location' : 'London' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Leyton' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'West End' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Uxbridge' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Feltham' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Hertfordshire' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Essex' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Bristol' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Edinburgh' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Glasgow' , 'region' : 'Scotland'} , ignore_index=True)
loc = loc.append({'location' : 'Hampshire' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Staffordshire' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Stoke On Trent' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Belfast' , 'region' : 'Northern Ireland'} , ignore_index=True)
loc = loc.append({'location' : 'Basingstoke' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'West Malling' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Telford' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Banbury' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Twickenham' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Kingston Upon Hull' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Ossett' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Keighley' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Northallerton' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'South Yorkshire' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Morley' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Cardiff' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Broughton' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Bath' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Cheadle' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Gloucestershire' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'St Neots' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Newbury' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Sidmouth' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Stratford' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Hertford' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Witham' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Dummer' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Oxfordshire' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Brighton' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Hatfield' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Wrexham' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Handforth' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Billingshurst' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Royal Tunbridge Wells' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'West Bromwich' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Shrewsbury' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Cambridgeshire' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Staines' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Saint Columb Major' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Spalding' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Thame' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Worksop' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Hoddesdon' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Devon' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Westbury' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Gibraltar' , 'region' : 'Gibraltar'} , ignore_index=True)
loc = loc.append({'location' : 'Cambridge Huntingdon St Neots Peterborough' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Salisbury' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Folkestone' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Poulton-Le-Fylde' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Brockenhurst' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Beckington' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Crewe' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Teesport' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Caernarfon' , 'region' : 'Wales'} , ignore_index=True)
loc = loc.append({'location' : 'Chester' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Billingham' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Erdington' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Pitsea' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Warwickshire' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Rushden' , 'region' : 'East Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Finchingfield' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'West Drayton' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Nuneaton' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Nether Poppleton' , 'region' : 'Yorkshire and The Humber'} , ignore_index=True)
loc = loc.append({'location' : 'Taunton' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'Widnes' , 'region' : 'North West'} , ignore_index=True)
loc = loc.append({'location' : 'Stratford-Upon-Avon' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Surrey' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'Wymondham' , 'region' : 'East of England'} , ignore_index=True)
loc = loc.append({'location' : 'Aldwych' , 'region' : 'London'} , ignore_index=True)
loc = loc.append({'location' : 'Halesowen' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Chandlers Ford' , 'region' : 'South East'} , ignore_index=True)
loc = loc.append({'location' : 'North East England' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'South West England' , 'region' : 'South West'} , ignore_index=True)
loc = loc.append({'location' : 'West Midlands' , 'region' : 'West Midlands'} , ignore_index=True)
loc = loc.append({'location' : 'Newcastle' , 'region' : 'North East'} , ignore_index=True)
loc = loc.append({'location' : 'Uk Wide' , 'region' : 'NaN'} , ignore_index=True)
loc = loc.append({'location' : 'England' , 'region' : 'NaN'} , ignore_index=True)

loc.location = loc.location.str.title()
loc['country'] = 'United Kingdom'
loc.to_csv(path + '/data/locations_UK.csv', index=False)